### ISSUE TITLE
WDTCR

### ISSUE THREAD

**Issue by t-a-e** [GyverLibs/GyverWDT#2]
C:\Users\�������\Documents\Arduino\libraries\GyverWDT-main\src/GyverWDT.h: In member function 'void GyverWDT::disable()':

C:\Users\�������\Documents\Arduino\libraries\GyverWDT-main\src/GyverWDT.h:135:7: error: 'WDTCSR' was not declared in this scope

       WDTCSR = ((1 << WDCE) | (1 << WDE));  // Разблокировка доступа к watchdog, см. документацию на МК

       ^~~~~~

C:\Users\�������\Documents\Arduino\libraries\GyverWDT-main\src/GyverWDT.h:135:7: note: suggested alternative: 'WDTCR'

       WDTCSR = ((1 << WDCE) | (1 << WDE));  // Разблокировка доступа к watchdog, см. документацию на МК

       ^~~~~~

       WDTCR

в 25/45/85 тиньке нет регистра WDTCSR там он называется WDTCR

**Comment by GyverLibs** [comment]
спасибо, пофиксили
